from typing import List, Dict

class BiometricProcessor:
    """
    Handles backend validation and storage of the biometric scores 
    generated by the frontend Web Worker.
    """
    def __init__(self):
        # Initialization for anomaly detection models in a real implementation
        pass

    def evaluate_score(self, current_score: int, history: List[int]) -> Dict[str, Any]:
        """
        Evaluate sudden drops in biometrics compared to historical average.
        """
        if current_score < 40:
            return {"action": "KILL_SESSION", "reason": "CRITICAL_BIOMETRIC_DROP"}
            
        if current_score < 65:
            return {"action": "REQUIRE_STEP_UP", "reason": "LOW_BIOMETRIC_CONFIDENCE"}

        if not history:
            return {"action": "OK"}
            
        avg = sum(history) / len(history)
        drop = avg - current_score
        
        if drop > 30:
            return {"action": "REQUIRE_STEP_UP", "reason": "SUDDEN_BIOMETRIC_DEVIATION"}
            
        return {"action": "OK"}
